// Assignment04/src/views/Profile.vue
<script>
import { defineComponent, reactive } from 'vue'
import { signUp } from '../services/user.service'
import { login } from '../services/user.service'

export default defineComponent({
  name: 'SignUpForm',
  setup() {
    const formFields = reactive({
      username: '',
      password: ''
    })

    const handleUpdate = async () => {
      if(formFields.username && formFields.password){
        const response = await updateProfile(formFields.username, formFields.password);
        if(response){
          await login(formFields.username, formFields.password);
        }
        else{
          console.log("Sign up failed");
        }
        console.log(response);
      }
      else{
        console.log("Please enter a username and password");
      }
    }

    return {
      formFields,
      handleUpdate
    }
  }
})
</script>

<template>
    <div class="flex flex-col gap-2">
      <h2 class="text-xl font-semibold">Profile</h2>
      <form class="flex flex-col gap-4" @submit.prevent="handleUpdate">
        <div>
          <label class="label">
            <span class="label-text">Username</span>
          </label>
          <input
            type="text"
            class="input input-bordered"
            name="username"
            v-model="formFields.username"
            disabled={true}
          />
        </div>
        <div>
          <label class="label">
            <span class="label-text">Password</span>
          </label>
          <input
            type="password"
            name="password"
            v-model="formFields.password"
            class="input input-bordered"
            placeholder="Enter your password"
          />
        </div>
        <button type="submit" class="btn btn-primary w-fit">Update</button>
      </form>
    </div>
</template>

// Assignment03/src/routes/profile.tsx
import { useEffect, useState } from 'react';
import { AppDispatch, RootState } from '../store/store';
import { useDispatch, useSelector } from 'react-redux';
import { getProfile, updateProfile } from '../store/user/user.action';
import { UserData } from '../types/user-data';

const Profile = () => {
  const dispatch = useDispatch<AppDispatch>();

  const currentUser: UserData = useSelector(
    (state: RootState) => state.user.currentUser
  );

  const [username, setUsername] = useState<string>('');
  const [password, setPassword] = useState<string>('');

  useEffect(() => {
    const fetchData = async () => {
      const action = await dispatch(getProfile(currentUser));
      const response: UserData = action.payload;
      setUsername(response.username);
      setPassword(response.password);
    };
    if(currentUser.userId && currentUser.token){
      fetchData();
    }
  }, [currentUser]);

  const handleUpdateProfile = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const data: UserData = {
      userId: currentUser.userId,
      username: username,
      password: password,
      token: currentUser.token,
      admin: false,
    };
    await dispatch(updateProfile(data));
  };

  const handleChange = (e: React.FormEvent<HTMLInputElement>) => {
    setPassword(e.currentTarget.value);
  };

  return (
    <div className="flex flex-col gap-2">
      <h2 className="text-xl font-semibold">Profile</h2>
      <form className="flex flex-col gap-4" onSubmit={handleUpdateProfile}>
        <div>
          <label className="label">
            <span className="label-text">Username</span>
          </label>
          <input
            type="text"
            className="input input-bordered"
            name="username"
            value={username}
            disabled={true}
          />
        </div>
        <div>
          <label className="label">
            <span className="label-text">Password</span>
          </label>
          <input
            type="password"
            className="input input-bordered"
            placeholder="Enter your username"
            name="password"
            value={password}
            onChange={handleChange}
          />
        </div>
        <button type="submit" className="btn btn-primary w-fit">
          Update
        </button>
      </form>
    </div>
  );
};

export default Profile;
