// Assignment03/src/components/sign-up-form.tsx
import { FormEvent, useState } from 'react';
import { useDispatch } from 'react-redux';
import { signUp, login } from '../store/user/user.action';
import { UserData } from '../types/user-data';
import { AppDispatch } from '../store/store';
import { toast } from 'react-hot-toast';

const defaultFormFields: UserData = {
  username: '',
  password: '',
};

const SignUpForm = () => {
  const dispatch = useDispatch<AppDispatch>();

  const [formFields, setFormFields] = useState(defaultFormFields);
  const { username, password } = formFields;

  const handleChange = (e: FormEvent<HTMLInputElement>) => {
    const { name, value } = e.currentTarget;
    setFormFields({ ...formFields, [name]: value });
  };

  const handleSignUp = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const response = await dispatch(signUp(formFields));

    if (response.meta.requestStatus === 'fulfilled') {
      await dispatch(login(response.payload));
    } else {
      toast.error('Sign up failed');
    }
  };

  return (
    <div className="flex flex-col gap-2">
      <h2 className="text-xl font-semibold">Sign Up</h2>
      <form className="flex flex-col gap-4" onSubmit={handleSignUp}>
        <div>
          <label className="label">
            <span className="label-text">Username</span>
          </label>
          <input
            type="text"
            className="input input-bordered"
            name="username"
            value={username}
            onChange={handleChange}
            placeholder="Enter your username"
          />
        </div>
        <div>
          <label className="label">
            <span className="label-text">Password</span>
          </label>
          <input
            type="password"
            name="password"
            value={password}
            onChange={handleChange}
            className="input input-bordered"
            placeholder="Enter your username"
          />
        </div>
        <button type="submit" className="btn btn-primary">
          Sign up
        </button>
      </form>
    </div>
  );
};

export default SignUpForm;

// Assignment04/src/components/SignUpForm.vue
<script>
import { defineComponent, reactive } from 'vue'
import { signUp } from '../services/user.service'
import { login } from '../services/user.service'

export default defineComponent({
  name: 'SignUpForm',
  setup() {
    const formFields = reactive({
      username: '',
      password: ''
    })

    const handleSignUp = async () => {
      console.log('Sign up successful: ', formFields.username, formFields.password);
      if(formFields.username && formFields.password){
        const response = await signUp(formFields.username, formFields.password);
        if(response.meta.requestStatus === 'fulfilled'){
          await login(formFields.username, formFields.password);
        }
        else{
          console.log("Sign up failed");
        }
        console.log(response);
      }
      else{
        console.log("Please enter a username and password");
      }
    }

    return {
      formFields,
      handleSignUp
    }
  }
})
</script>

<template>
  <div class="flex flex-col gap-2">
    <h2 class="text-xl font-semibold">Sign Up</h2>
    <form class="flex flex-col gap-4" @submit.prevent="handleSignUp">
      <div>
        <label class="label">
          <span class="label-text">Username</span>
        </label>
        <input
          type="text"
          class="input input-bordered"
          name="username"
          v-model="formFields.username"
          placeholder="Enter your username"
        />
      </div>
      <div>
        <label class="label">
          <span class="label-text">Password</span>
        </label>
        <input
          type="password"
          name="password"
          v-model="formFields.password"
          class="input input-bordered"
          placeholder="Enter your password"
        />
      </div>
      <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
  </div>
</template>
